### ISSUE TITLE
https is rewritten to http

### ISSUE THREAD

**Issue by lukipuki** [arnost00/members#4]
The form for editing a race (at `race_edit.php`) saves an https URL as `http://...`. All our links to https://is.orienteering.sk  are broken.

The issue lies in the function `cononize_url` which has [the string `http` hard-coded](https://github.com/arnost00/members/blob/af6c256cd11c03d5ec460d192c45c1dd82fcfbfa/url.inc.php#L8), so this can affect code calling `cononize_url` with `$scheme > 0`.

**Comment by jurakin** [comment]
The problem should be in [cononize_url($odkaz);](https://github.com/arnost00/members/blob/af6c256cd11c03d5ec460d192c45c1dd82fcfbfa/race_edit_exc.php#L90). The second argument `1` should be added to accept an existing protocol and only add `http://...` when no other is specified.

```
$odkaz = cononize_url($odkaz, 1);
```
