### ISSUE TITLE
On Small admin page with all Club members hide Hidden members in default

### ISSUE THREAD

**Issue by xkenia** [arnost00/members#8]
Na strance Spravce -> Clenska zakladna v zakladu nezobrazovat skryte cleny, ale zobrazit az po zaskrtnuti noveho checkboxu.

**Comment by arnost00** [comment]
Opraveno v unoru 2023 v commitu a969580a250f9d39e6121bff758750e4161473fb
Sice ne check box, ale tlacitko.
Asi by stacilo aby na ZBM prisla spravna verze a bude to funkcni :)
